# Generated by Django 4.1.6 on 2023-02-09 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("759b8a9d-e6cd-4890-ad4d-66594ecbaf03"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
