# Generated by Django 4.1.6 on 2023-02-09 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("0a6db6e0-fcdb-44cd-a373-23be1e0feb89"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=255)),
            ],
        ),
    ]
